apiVersion: v1
kind: Service
metadata:
  name: mail-service
spec:
  type: ClusterIP
  selector:
    app: mail-service
  ports:
    - name: http-mail
      port: 8081           # service port
      targetPort: 8081   # container port